on: workflow_dispatch

jobs:
  first_autobot:
        runs-on:  ubuntu-latest
        steps:
          - name: Return of the autobots
            run:  echo "Hi, my name is Optimus Prime"
          - name: Dark side of the moon
            run: echo "We have suffered losses, but we have not lost the war."
          - name: Checkout
            uses: actions/checkout@v2
          - name: Build Docker
            run: docker build . --file Dockerfile
          - name: Execute Test Cases
            run: docker run --rm -v pwd:/workdir bash -c "robot workdir/TestCases"
