on: workflow_dispatch

env:

  # The image name

  IMAGE_NAME: docker-robot-framework:ci

jobs:
  first_autobot:
        runs-on:  ubuntu-latest
        steps:
          - name: Return of the autobots
            run:  echo "Hi, my name is Optimus Prime"
          - name: Dark side of the moon
            run: echo "We have suffered losses, but we have not lost the war."
          - name: Build Docker
            run: docker build . --tag $IMAGE_NAME --file Dockerfile
