name: CI Workflow

on:
  push:
    branches:
      - dev 
    pull_request:
      - dev 
    # workflow_dispatch

jobs:
  build-and-test:
    runs-on: windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        run: echo "Hello"

      - name: Build
        run: |
          # Add your build commands here
          echo "Building the project..."

      - name: TestCases
        run: |
          P1_TO01_MH_Tests.robot