name: CI Workflow

on:
  push:
    branches:
      - dev 
    pull_request:
      - dev 

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Robot Framework
        run: |
          pip install robotframework
          pip install robotframework-seleniumlibrary

      - name: Run Robot Framework Tests
        run: robot P1_TO01_MH_Tests.robot