name: CI Workflow

on:
  push:
    branches:
      - dev 
  pull_request:
    branches:
      - dev 

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Robot Framework
        run: |
          pip install robotframework
          pip install robotframework-seleniumlibrary

      - name: Install dependecies 
        run:
         python -m pip install --upgrade pip
      
      - name: Set up Chrome WebDriver
        run: 
          https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
          curl -sS -o chromedriver.zip "https://chromedriver.storage.googleapis.com/$LATEST_CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
          unzip chromedriver.zip
          chmod +x chromedriver
          sudo mv chromedriver /usr/local/bin/

      - name: Run Robot Framework Tests
        run: robot TestCases/P1_TO01_MH_Tests.robot
