name: Docker Build

on: workflow_dispatch

jobs:
     first_action:
                  runs-on: ubuntu-latest
                  steps:
                        name: Return Of The Dark Knight
                        run: echo "I am Batman"