name: CI Workflow

on:
  push:
    branches:
      - dev 
  pull_request:
    branches:
      - dev 

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Robot Framework
        run: |
          pip install robotframework
          pip install robotframework-seleniumlibrary

      - name: Install dependecies 
        run:
         python -m pip install --upgrade pip

       - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: docker.io/library/your_image_name:tag

      - name: Run Robot Framework Tests
        run: |
          docker run -v $PWD:/app docker.io/library/your_image_name:tag \
          robot TestCases/P1_TO01_MH_Tests.robot

      - name: Run Robot Framework Tests
        run: robot TestCases/P1_TO01_MH_Tests.robot
